# NUMPY

In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.6'

## Convert normal array to numpy array

In [3]:
arr = [1, 2, 3, 4, 5] # this is the normal array
arr

[1, 2, 3, 4, 5]

In [4]:
narr = np.array(arr) # this is the numpy array
narr

array([1, 2, 3, 4, 5])

In [5]:
arr2d = [[1,2,3], [4,5,6], [7,8,9]] # normat 2d array
arr2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
narr2d= np.array(arr2d) # this is the 2D numpy array
narr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange method

In [7]:
# arange method ta python er for loop er range method er moto. numpy er range method version holo arange.

# arange er syntax holo: np.arange(start, stop, step)

np.arange(10) # 0 theke 10 porjonto number generate korbe, 10 ta include hobe na. default step size holo 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10,15) 

array([10, 11, 12, 13, 14])

In [9]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

## zeros and ones method

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
# zeros method theke amra 2d array or list ow paite pari

np.zeros([3,4]) # 3 row and 4 column er 2d array generate korbe

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# not only 2d array, amra chaile 3d,4d,5d,...,nd array o generate korte pari.

np.zeros([3,4,5]) # 3d array generate korbe. 3 ta 4x5 er matrix generate korbe

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [13]:
# zeros er moto ones method o ache. same as zeros. just 0 er jaygay 1 generate korbe.

np.ones(10) # 1D array generate korbe, 10 ta 1 thakbe

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## linspace and eye method

In [14]:
# linspace method ta amra use korte pari, jodi amra kono range er moddhe specific number of equally spaced number generate korte chai.

# linspace er syntax holo: np.linspace(start, stop, num)

np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [15]:
# eye() method diye amra identity matrix generate korte pari. identity matrix holo square matrix, jekhane diagonal er element gulo 1 and baki sob element gulo 0 thake.

'''
I3 = [[1. 0. 0.]
      [0. 1. 0.]
      [0. 0. 1.]]
'''

np.eye(3) # 3x3 identity matrix generate korbe

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random module or method (vvi)

In [ ]:
# random() method diye amra random number generate korte pari.

# rand() method ta uniform distribution er random number generate kore. 

np.random.rand() # ekhane random ekta value pabo eta 0 to 1 er moddhe hobe.

0.11823131945600163

In [17]:
np.random.rand(5) # ekhane 5 ta random value pabo, 0 to 1 er moddhe hobe.

array([0.19309335, 0.50104927, 0.82057561, 0.37586223, 0.84327116])

In [18]:
np.random.rand(10,2) # ekhane 10 row and 2 column er random value pabo, 0 to 1 er moddhe hobe.

array([[0.40199825, 0.91112166],
       [0.51871146, 0.62888711],
       [0.43591355, 0.42356878],
       [0.88591542, 0.50903328],
       [0.64862671, 0.24501518],
       [0.89674726, 0.39627761],
       [0.63014534, 0.1061658 ],
       [0.46395863, 0.89073329],
       [0.27495167, 0.37821762],
       [0.08967718, 0.15262636]])

In [ ]:
# negative chaile randn hobe. 

# randn() method ta normal distribution or gaussian distribution er random number generate kore.

np.random.randn() # ekhane random ekta value pabo eta -1 to 1 er moddhe hobe.

-1.5875688958684087

### randint

In [20]:
# ekta range er moddhe random number generate korte hole amra randint method use korte pari.

# randint er syntax holo: np.random.randint(low, high=None, size=None, dtype=int)

np.random.randint(1,10) # ekhane 1 to 10 er moddhe random ekta value pabo, 10 ta include hobe na.

8

In [21]:
np.random.randint(1,10,5) # ekhane 1 to 10 er moddhe random 5 ta value pabo, 10 ta include hobe na.

array([2, 3, 3, 1, 8])

In [23]:
np.random.randint(1,10,[5,2]) # ekhane 1 to 10 er moddhe random 5x2 er matrix pabo, 10 ta include hobe na.

array([[2, 8],
       [5, 1],
       [8, 9],
       [2, 6],
       [4, 4]])

## shape manipulation

In [ ]:
# amra jokhon real project er dataset niye kaj korbo tokhon dataset er datagula kon dimension(row * column) e ase sheta directly dekhte parbo na. dimension dekhte shape attribute use korte hobe.

random_array = np.random.randint(10,21,[6,3,4]) # ekhane 10 to 21 er moddhe random 6x3x4 er 3d matrix pabo, 21 ta include hobe na.
random_array.shape 

(6, 3, 4)

In [26]:
random_array 

array([[[11, 14, 18, 11],
        [17, 20, 20, 20],
        [17, 19, 19, 17]],

       [[10, 17, 11, 10],
        [13, 14, 18, 11],
        [15, 15, 13, 19]],

       [[20, 12, 19, 18],
        [14, 14, 17, 15],
        [16, 10, 13, 16]],

       [[15, 11, 11, 14],
        [10, 10, 20, 15],
        [10, 15, 15, 10]],

       [[11, 12, 19, 11],
        [18, 11, 12, 10],
        [17, 10, 19, 17]],

       [[17, 14, 13, 11],
        [15, 19, 13, 17],
        [14, 11, 16, 14]]])

In [28]:
# reshape method diye amra kono array er shape change korte pari. but total number of element same thakbe. for example amader random_array er shape 6x3x4, mane total element 6*3*4=72. amra chaile 72 ta element ke 2d array te convert korte pari, for example 8x9 or 12x6 etc. but total element same thakbe.

# most important shape change korte hole total element number same thakte hobe.

new_shape_array = random_array.reshape(12,6) 

new_shape_array

array([[11, 14, 18, 11, 17, 20],
       [20, 20, 17, 19, 19, 17],
       [10, 17, 11, 10, 13, 14],
       [18, 11, 15, 15, 13, 19],
       [20, 12, 19, 18, 14, 14],
       [17, 15, 16, 10, 13, 16],
       [15, 11, 11, 14, 10, 10],
       [20, 15, 10, 15, 15, 10],
       [11, 12, 19, 11, 18, 11],
       [12, 10, 17, 10, 19, 17],
       [17, 14, 13, 11, 15, 19],
       [13, 17, 14, 11, 16, 14]])

In [29]:
# find out the maximum and minimum value from the new_shape_array.

new_shape_array.max() # maximum value

np.int64(20)

In [30]:
new_shape_array.min() # minimum value

np.int64(10)

In [34]:
# maximum and minimum value er index find out korte hole amra argmax() and argmin() method use korte pari. 

# but argmax() and argmin() method ta 1D array er jonno kaj kore. tai amra new_shape_array ke 1D array te convert kore nibo.

new_shape_array_1d = new_shape_array.reshape(72) # ekhane 72 ta element ke 1D array te convert korlam.

new_shape_array_1d

array([11, 14, 18, 11, 17, 20, 20, 20, 17, 19, 19, 17, 10, 17, 11, 10, 13,
       14, 18, 11, 15, 15, 13, 19, 20, 12, 19, 18, 14, 14, 17, 15, 16, 10,
       13, 16, 15, 11, 11, 14, 10, 10, 20, 15, 10, 15, 15, 10, 11, 12, 19,
       11, 18, 11, 12, 10, 17, 10, 19, 17, 17, 14, 13, 11, 15, 19, 13, 17,
       14, 11, 16, 14])

In [36]:
new_shape_array_1d.argmax() # maximum value er index

np.int64(5)

In [37]:
new_shape_array_1d.argmin() # minimum value er index

np.int64(12)