## Indexing and Slicing

In [1]:
import numpy as np

### indexing and slicing of 1d array

In [9]:
# numpy er 1d array indexing and slicing kora python er normal array er motoi

arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
arr[5]

np.int64(5)

In [11]:
# slicing syntax: arr[start:stop:step]  # start and stop index by default 0 and len(arr) respectively, step by default 1

arr[1:5]

array([1, 2, 3, 4])

### copy method

In [12]:
# numpy te ekta odvut problem ase. ami ekta array ke new ekta variable e assign korle, duita variable ei same memory address ke point kore. orthat ami new array ta cahnge korle main array ow change hoye jay. but eta raw python e hoy na. etar solution hocche copy() method use kora. 

new_arr = arr[3:8].copy()
new_arr[0] = 999

new_arr

array([999,   4,   5,   6,   7])

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])