In [15]:
import numpy as np

## Indexing and Slicing

- defference between indexing and slicing: indexing e ami kono ekta position er ekta value ei dekhte pabo. but slicing e multiple element dekhte pabo

### indexing and slicing of 1d array

In [9]:
# numpy er 1d array indexing and slicing kora python er normal array er motoi

arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
arr[5]

np.int64(5)

In [11]:
# slicing syntax: arr[start:stop:step]  # start and stop index by default 0 and len(arr) respectively, step by default 1

arr[1:5]

array([1, 2, 3, 4])

### copy method

In [12]:
# numpy te ekta odvut problem ase. ami ekta array ke new ekta variable e assign korle, duita variable ei same memory address ke point kore. orthat ami new array ta cahnge korle main array ow change hoye jay. but eta raw python e hoy na. etar solution hocche copy() method use kora. 

new_arr = arr[3:8].copy()
new_arr[0] = 999

new_arr

array([999,   4,   5,   6,   7])

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Matrix(2d, 3d or nd arrays) Indexing and Slicing

In [2]:
matrix = np.array([[1,2,3,4], [10,20,30,40], [100,200,300,400], [1000,2000,3000,4000]])
matrix

array([[   1,    2,    3,    4],
       [  10,   20,   30,   40],
       [ 100,  200,  300,  400],
       [1000, 2000, 3000, 4000]])

In [3]:
# normal indexing in 2d array

third_row = matrix[2]
third_row

array([100, 200, 300, 400])

In [5]:
third_row[1]

np.int64(200)

In [6]:
#directly

matrix[2][1]

np.int64(200)

In [8]:
# third bracket na diye comma diye numpy te kora jay. third bracket dewa jhamela.

matrix[2, 1] # 2nd row, 1st column er value or 2nd row er 1st element

np.int64(200)

### Slicing

In [9]:
matrix2 = np.array([[1,2,3,4], [10,20,30,40], [100,200,300,400], [1000,2000,3000,4000]])
matrix2

array([[   1,    2,    3,    4],
       [  10,   20,   30,   40],
       [ 100,  200,  300,  400],
       [1000, 2000, 3000, 4000]])

In [10]:
# ekhon ami uporer matrix ta theke just 20, 30 and 200,300 slice kora lagbe.

# slicing ta duivabe kora jay. basic python diye. and easy numpy er syntax diye. aage basic ta dekhbo.

#basic:
new_array = []
rows = matrix2[1:3] # 1st and 2nd row

for row in rows:
    new_array.append(row[1:3]) # 1st and 2nd column

new_array

[array([20, 30]), array([200, 300])]

In [12]:
# numpy er syntax: array[start_row:end_row, start_col:end_col]

matrix2[1:3, 1:3]

array([[ 20,  30],
       [200, 300]])

In [14]:
# ami shob row rakhbo but only third column ta rakhbo.

matrix2[:, 2]  # syntax e shurute row thake, so shob row nile amake semicolon ta dite hobe.

array([   3,   30,  300, 3000])