In [2]:
import numpy as np

In [3]:
matrix = np.random.randint(1,100, size=(4,4))
matrix

array([[21, 47, 85, 18],
       [70, 39, 36, 42],
       [95, 58, 46, 96],
       [23, 63, 60,  3]])

In [4]:
matrix[3,2]

np.int64(60)

In [7]:
matrix[0:2,1:2]

array([[47],
       [39]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [15]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.random.randint(10,20, size=[3,3])

array([[17, 15, 12],
       [13, 10, 12],
       [16, 12, 19]])