# NUMPY

In [139]:
import numpy as np
np.random.seed(0)

In [140]:
np.__version__

'2.4.6'

## Convert normal array to numpy array

In [141]:
arr = [1, 2, 3, 4, 5] # this is the normal array
arr

[1, 2, 3, 4, 5]

In [142]:
narr = np.array(arr) # this is the numpy array
narr

array([1, 2, 3, 4, 5])

In [143]:
arr2d = [[1,2,3], [4,5,6], [7,8,9]] # normat 2d array
arr2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [144]:
narr2d= np.array(arr2d) # this is the 2D numpy array
narr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange method

In [145]:
# arange method ta python er for loop er range method er moto. numpy er range method version holo arange.

# arange er syntax holo: np.arange(start, stop, step)

np.arange(10) # 0 theke 10 porjonto number generate korbe, 10 ta include hobe na. default step size holo 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
np.arange(10,15) 

array([10, 11, 12, 13, 14])

In [147]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

## zeros and ones method

In [148]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [149]:
# zeros method theke amra 2d array or list ow paite pari

np.zeros([3,4]) # 3 row and 4 column er 2d array generate korbe

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [150]:
# not only 2d array, amra chaile 3d,4d,5d,...,nd array o generate korte pari.

np.zeros([3,4,5]) # 3d array generate korbe. 3 ta 4x5 er matrix generate korbe

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [151]:
# zeros er moto ones method o ache. same as zeros. just 0 er jaygay 1 generate korbe.

np.ones(10) # 1D array generate korbe, 10 ta 1 thakbe

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## linspace and eye method

In [152]:
# linspace method ta amra use korte pari, jodi amra kono range er moddhe specific number of equally spaced number generate korte chai.

# linspace er syntax holo: np.linspace(start, stop, num)

np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [153]:
# eye() method diye amra identity matrix generate korte pari. identity matrix holo square matrix, jekhane diagonal er element gulo 1 and baki sob element gulo 0 thake.

'''
I3 = [[1. 0. 0.]
      [0. 1. 0.]
      [0. 0. 1.]]
'''

np.eye(3) # 3x3 identity matrix generate korbe

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random module or method (vvi)

### np.random.rand()

In [154]:
# random() method diye amra random number generate korte pari.

# rand() method ta uniform distribution er random number generate kore.
# uniform distrubution holo: data ekta range er moddhe thake and oi range er moddhe jekono value pawar probability same thake. 

np.random.rand() # ekhane random ekta value pabo eta 0 to 1 er moddhe hobe.

0.5488135039273248

In [155]:
np.random.rand(5) # ekhane 5 ta random value pabo, 0 to 1 er moddhe hobe.

array([0.71518937, 0.60276338, 0.54488318, 0.4236548 , 0.64589411])

In [156]:
np.random.rand(10,2) # ekhane 10 row and 2 column er random value pabo, 0 to 1 er moddhe hobe.

array([[0.43758721, 0.891773  ],
       [0.96366276, 0.38344152],
       [0.79172504, 0.52889492],
       [0.56804456, 0.92559664],
       [0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985],
       [0.77815675, 0.87001215],
       [0.97861834, 0.79915856],
       [0.46147936, 0.78052918],
       [0.11827443, 0.63992102]])

In [157]:
# negative chaile randn hobe. 

# randn() method ta normal distribution or gaussian distribution er random number generate kore.

np.random.randn() # ekhane random ekta value pabo eta -1 to 1 er moddhe hobe.

-2.5529898158340787

### np.random.exponential()

In [158]:
"""
    NumPy Random: rand() vs exponential()
    =====================================

    দুটো function-ই random value generate করে, কিন্তু তারা
    ভিন্ন distribution থেকে value generate করে।

    --------------------------------------------------------
    1. np.random.rand()
    --------------------------------------------------------

    rand() → Uniform distribution থেকে random value দেয়।

    Uniform distribution মানে:
    - 0 থেকে 1-এর মধ্যে value আসবে।
    - এই range-এর value-গুলো প্রায় সমানভাবে likely।

    Examples:

    np.random.rand()
    → ১টি random value
    → 0 ≤ value < 1

    np.random.rand(5)
    → ৫টি random value
    → সবগুলো 0 ≤ value < 1

    np.random.rand(10, 2)
    → 10 rows × 2 columns
    → মোট 20টি random value
    → সবগুলো 0 ≤ value < 1


    Important:
    rand() এ size= ব্যবহার করা যায় না।

    যেমন:
    np.random.rand(5)          # valid
    np.random.rand(size=5)     # invalid

    কারণ rand() function-এর syntax হলো:

    np.random.rand(d0, d1, d2, ...)

    অর্থাৎ এখানে সরাসরি dimensions/shape দিতে হয়।


    --------------------------------------------------------
    2. np.random.exponential()
    --------------------------------------------------------

    exponential() → Exponential distribution থেকে
    random value দেয়।

    এখানে value-এর fixed upper limit নেই।

    মূল rule:

    value ≥ 0

    অর্থাৎ:
    - negative value আসবে না।
    - 0 বা তার কাছাকাছি ছোট value বেশি likely।
    - বড় value আসতে পারে, কিন্তু বড় value-এর probability কম।
    - কোনো fixed maximum নেই।

    note: exponential distribution e 1-10 range dilam. ekhane 10 ashtei pare but tar probability kom. 1 er kache value asha beshi likely.
    graph:
                    frequency
                ↑
                |████████
                |██████
                |████
                |███
                |██
                |█
                +--------------------→ value
                    0   1   2   3   4...

    Examples:
    np.random.exponential()
    → ১টি random value

    np.random.exponential(size=5)
    → ৫টি random value

    np.random.exponential(size=(10, 2))
    → 10 rows × 2 columns
    → মোট 20টি random value


    এ ধরনের value আসতে পারে:

    [0.2, 0.7, 0.3, 1.8, 0.5, 4.2, 0.1, ...]

    এখানে বেশিরভাগ value ছোট হবে,
    মাঝে মাঝে বড় value আসতে পারে।


    --------------------------------------------------------
    3. rand() vs exponential()
    --------------------------------------------------------

    np.random.rand()

    → Uniform distribution
    → 0 ≤ value < 1
    → fixed range আছে
    → values প্রায় সমানভাবে distributed


    np.random.exponential()

    → Exponential distribution
    → value ≥ 0
    → fixed upper limit নেই
    → ছোট values বেশি likely
    → বড় values progressively কম likely


    --------------------------------------------------------
    4. সবচেয়ে সহজভাবে মনে রাখার নিয়ম
    --------------------------------------------------------

    rand()
    → "0 থেকে 1-এর মধ্যে random value"

    exponential()
    → "0 বা তার বেশি random value,
    যেখানে ছোট value বেশি এবং বড় value কম"


"""

pass

In [159]:
np.random.exponential(size=5)

array([0.30728035, 1.48825484, 0.60908242, 0.84033471, 0.01896857])

### randint

In [160]:
# ekta range er moddhe random number generate korte hole amra randint method use korte pari.

# randint er syntax holo: np.random.randint(low, high=None, size=None, dtype=int)

np.random.randint(1,10) # ekhane 1 to 10 er moddhe random ekta value pabo, 10 ta include hobe na.

6

In [161]:
np.random.randint(1,10,5) # ekhane 1 to 10 er moddhe random 5 ta value pabo, 10 ta include hobe na.

array([6, 7, 9, 5, 2])

In [162]:
np.random.randint(1,10,[5,2]) # ekhane 1 to 10 er moddhe random 5x2 er matrix pabo, 10 ta include hobe na.

array([[5, 9],
       [2, 2],
       [8, 4],
       [7, 8],
       [3, 1]])

In [163]:
# randint ta khubi important. array or matrix banaite eitai use korbo. so syntax gula jana lagbe.

# nicher 4 tai same output dibe and 4 tai valid. but prothom ta convention.
matrix = np.random.randint(1,100, size = (3,3)) # convention
matrix = np.random.randint(1,100, size = [3,3])
matrix = np.random.randint(1,100, (3,3))
matrix = np.random.randint(1,100, [3,3])

## shape manipulation

In [164]:
# amra jokhon real project er dataset niye kaj korbo tokhon dataset er datagula kon dimension(row * column) e ase sheta directly dekhte parbo na. dimension dekhte shape attribute use korte hobe.

random_array = np.random.randint(10,21,[6,3,4]) # ekhane 10 to 21 er moddhe random 6x3x4 er 3d matrix pabo, 21 ta include hobe na.
random_array 

array([[[13, 12, 20, 10],
        [17, 15, 19, 10],
        [20, 12, 20, 17]],

       [[12, 19, 12, 13],
        [13, 12, 13, 14],
        [11, 12, 19, 20]],

       [[11, 14, 20, 16],
        [18, 12, 13, 10],
        [10, 16, 10, 16]],

       [[13, 20, 13, 18],
        [18, 18, 12, 13],
        [12, 10, 18, 18]],

       [[13, 18, 20, 12],
        [18, 14, 13, 10],
        [14, 13, 16, 19]],

       [[18, 10, 18, 15],
        [19, 10, 19, 16],
        [15, 13, 11, 18]]])

In [165]:
random_array.shape  

(6, 3, 4)

In [166]:
# reshape method diye amra kono array er shape change korte pari. but total number of element same thakbe. for example amader random_array er shape 6x3x4, mane total element 6*3*4=72. amra chaile 72 ta element ke 2d array te convert korte pari, for example 8x9 or 12x6 etc. but total element same thakbe.

# most important shape change korte hole total element number same thakte hobe.

new_shape_array = random_array.reshape(12,6) 

new_shape_array

array([[13, 12, 20, 10, 17, 15],
       [19, 10, 20, 12, 20, 17],
       [12, 19, 12, 13, 13, 12],
       [13, 14, 11, 12, 19, 20],
       [11, 14, 20, 16, 18, 12],
       [13, 10, 10, 16, 10, 16],
       [13, 20, 13, 18, 18, 18],
       [12, 13, 12, 10, 18, 18],
       [13, 18, 20, 12, 18, 14],
       [13, 10, 14, 13, 16, 19],
       [18, 10, 18, 15, 19, 10],
       [19, 16, 15, 13, 11, 18]])

In [167]:
# find out the maximum and minimum value from the new_shape_array.

new_shape_array.max() # maximum value

np.int64(20)

In [168]:
new_shape_array.min() # minimum value

np.int64(10)

In [169]:
# maximum and minimum value er index find out korte hole amra argmax() and argmin() method use korte pari. 

# but argmax() and argmin() method ta 1D array er jonno kaj kore. tai amra new_shape_array ke 1D array te convert kore nibo.

new_shape_array_1d = new_shape_array.reshape(72) # ekhane 72 ta element ke 1D array te convert korlam.

new_shape_array_1d

array([13, 12, 20, 10, 17, 15, 19, 10, 20, 12, 20, 17, 12, 19, 12, 13, 13,
       12, 13, 14, 11, 12, 19, 20, 11, 14, 20, 16, 18, 12, 13, 10, 10, 16,
       10, 16, 13, 20, 13, 18, 18, 18, 12, 13, 12, 10, 18, 18, 13, 18, 20,
       12, 18, 14, 13, 10, 14, 13, 16, 19, 18, 10, 18, 15, 19, 10, 19, 16,
       15, 13, 11, 18])

In [170]:
new_shape_array_1d.argmax() # maximum value er index

np.int64(2)

In [171]:
new_shape_array_1d.argmin() # minimum value er index

np.int64(3)

### reshape(-1,1)

In [172]:
"""
    reshape(-1, 1) মানে:
        -1 → কতটি row লাগবে, NumPy নিজে calculate করবে
        1 → 1টি column থাকবে

    Example:
        original_data.shape
        → (1000,)

        original_data.reshape(-1, 1)
        → (1000, 1)

    অর্থাৎ 1000টি element-কে 1টি column-এ সাজানো হলো।

    কেন reshape(1000, 1) এর বদলে reshape(-1, 1)?
        reshape(1000, 1)
        → 1000টি row hard-code করা হয়েছে।

        reshape(-1, 1)
        → row সংখ্যা NumPy নিজে বের করে।
        → data-এর size পরিবর্তন হলেও কাজ করবে।

    তাই reshape(-1, 1) বেশি flexible এবং practical।

    মনে রাখো:
        reshape(-1, 1)
        → "1টি column রাখো, row সংখ্যা তুমি নিজে বের করো।"
"""

'\n    reshape(-1, 1) মানে:\n        -1 → কতটি row লাগবে, NumPy নিজে calculate করবে\n        1 → 1টি column থাকবে\n\n    Example:\n        original_data.shape\n        → (1000,)\n\n        original_data.reshape(-1, 1)\n        → (1000, 1)\n\n    অর্থাৎ 1000টি element-কে 1টি column-এ সাজানো হলো।\n\n    কেন reshape(1000, 1) এর বদলে reshape(-1, 1)?\n        reshape(1000, 1)\n        → 1000টি row hard-code করা হয়েছে।\n\n        reshape(-1, 1)\n        → row সংখ্যা NumPy নিজে বের করে।\n        → data-এর size পরিবর্তন হলেও কাজ করবে।\n\n    তাই reshape(-1, 1) বেশি flexible এবং practical।\n\n    মনে রাখো:\n        reshape(-1, 1)\n        → "1টি column রাখো, row সংখ্যা তুমি নিজে বের করো।"\n'

In [173]:
data = np.random.exponential(size=1000)

In [174]:
data.shape # ekhane 1000 ta element ase, so shape (1000,)

(1000,)

In [176]:
data_2d = data.reshape(-1, 1)

In [177]:
data_2d.shape

(1000, 1)

In [181]:
data

array([5.51395998e-01, 9.32402873e-01, 1.93797790e-02, 3.58927217e-01,
       1.07932020e+00, 3.42599621e-01, 9.62375061e-01, 5.59961074e-01,
       1.45573973e-01, 3.54224130e-01, 8.43888471e-01, 8.93729074e-01,
       8.54079719e-01, 1.05900940e+00, 1.05584960e+00, 5.64610503e-01,
       2.26863397e+00, 4.58172881e-01, 5.72461562e-01, 2.22491463e+00,
       1.64089756e+00, 1.21701949e+00, 1.05612644e-01, 2.51928214e+00,
       1.25260753e+00, 6.76539373e+00, 1.61870087e-01, 2.02590879e+00,
       1.77325579e-01, 9.55966416e-01, 1.32183710e-01, 1.88392890e+00,
       1.64671909e+00, 8.41880948e-01, 5.22870029e-01, 7.16753899e-02,
       1.19543857e+00, 6.04299076e-01, 1.28033418e+00, 2.01277274e+00,
       3.70996030e+00, 1.93657723e+00, 1.17832346e-02, 4.46252829e-01,
       1.30929837e+00, 1.88294975e-01, 7.36131107e-01, 5.58700553e-02,
       2.23139207e-01, 1.86954708e-02, 1.57841273e+00, 2.53505712e-01,
       4.23657105e-01, 2.63221887e+00, 1.21879681e+00, 3.23568104e-02,
      

In [182]:
data_2d

array([[5.51395998e-01],
       [9.32402873e-01],
       [1.93797790e-02],
       [3.58927217e-01],
       [1.07932020e+00],
       [3.42599621e-01],
       [9.62375061e-01],
       [5.59961074e-01],
       [1.45573973e-01],
       [3.54224130e-01],
       [8.43888471e-01],
       [8.93729074e-01],
       [8.54079719e-01],
       [1.05900940e+00],
       [1.05584960e+00],
       [5.64610503e-01],
       [2.26863397e+00],
       [4.58172881e-01],
       [5.72461562e-01],
       [2.22491463e+00],
       [1.64089756e+00],
       [1.21701949e+00],
       [1.05612644e-01],
       [2.51928214e+00],
       [1.25260753e+00],
       [6.76539373e+00],
       [1.61870087e-01],
       [2.02590879e+00],
       [1.77325579e-01],
       [9.55966416e-01],
       [1.32183710e-01],
       [1.88392890e+00],
       [1.64671909e+00],
       [8.41880948e-01],
       [5.22870029e-01],
       [7.16753899e-02],
       [1.19543857e+00],
       [6.04299076e-01],
       [1.28033418e+00],
       [2.01277274e+00],
