In [1]:
import numpy as np

In [8]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

## vector operation

In [5]:
# Scalar Multiplication
print("Scalar multiplication (2 * u):")
print(2 * u)

Scalar multiplication (2 * u):
[ 4  8 10 12]


In [6]:
# Element-wise Addition
print("Addition (u + v):")
print(u + v)

Addition (u + v):
[3 4 5 8]


In [7]:
# NumPy-এর ডিফল্ট এলিমেন্ট-ওয়াইজ মাল্টিপ্লিকেশন (ডট প্রোডাক্ট নয়)
print("Element-wise multiplication (u * v):")
print(u * v)

Element-wise multiplication (u * v):
[ 2  0  0 12]


## 2. Vector-Vector Multiplication (Dot Product)

In [ ]:
# duita vector er dot product e scalar value pawa jay.
# and duita vector er cross product e vector value pawa jay.

"""
Vector Representation: Physics vs Machine Learning
===============================================

    Physics-এ:
        Vector সাধারণত Unit Vector (i, j, k) ব্যবহার করে represent করা হয়।

        Example:
            A = 2i + 3j + 4k


    Machine Learning / NumPy-তে:
        Vector সাধারণত Array-এর মাধ্যমে represent করা হয়।

        Example:
            A = np.array([2, 3, 4])

        এখানে:

            [2, 3, 4]
            ↓  ↓  ↓
            x  y  z
            ↓  ↓  ↓
            i  j  k


    অর্থাৎ, Physics এবং ML/NumPy-তে representation আলাদা হলেও
    দুটো একই Mathematical Vector-কে represent করে।

        Physics:
            A = 2i + 3j + 4k

        NumPy:
            A = np.array([2, 3, 4])


Dot Product:
-------------

    Physics-এ:
        A · B = AxBx + AyBy + AzBz

    NumPy-তে:
        A.dot(B)

    Example:
        A = np.array([2, 3, 4])
        B = np.array([1, 2, 5])

        A.dot(B)

        = (2×1) + (3×2) + (4×5)
        = 2 + 6 + 20
        = 28


মূল ধারণা:
-----------

    Physics-এ আমরা Vector-এর direction এবং components বোঝানোর জন্য
    Unit Vector (i, j, k) ব্যবহার করি।

    ML/NumPy-তে আমরা সাধারণত সেই Vector-এর numerical components
    সরাসরি Array-এর মধ্যে রাখি।

        Physics:
            2i + 3j + 4k

        ML/NumPy:
            [2, 3, 4]

        → দুটোই একই Vector-এর representation।

"""

In [ ]:
# NumPy-এর বিল্ট-ইন .dot() মেথড ব্যবহার করে ডট প্রোডাক্ট
print("NumPy dot() method result:")
print(u.dot(v))

In [ ]:
# কাস্টম ফাংশন দিয়ে ডট প্রোডাক্ট বের করা
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]  # ডাইমেনশন ঠিক আছে কিনা চেক করা
    
    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
        
    return result

print("Custom vector-vector multiplication result:")
print(vector_vector_multiplication(u, v))



## 3. Matrix-Vector Multiplication

In [ ]:
# একটি ৩x৪ ম্যাট্রিক্স ডিফাইন করা
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

print("Matrix U shape:", U.shape)

# কাস্টম ফাংশন দিয়ে ম্যাট্রিক্স-ভেক্টর মাল্টিপ্লিকেশন
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
        
    return result

print("Custom matrix-vector multiplication:")
print(matrix_vector_multiplication(U, v))

# NumPy-এর .dot() মেথড ব্যবহার করে
print("NumPy matrix-vector dot() result:")
print(U.dot(v))

## 4. Matrix-Matrix Multiplication

In [ ]:
# একটি ৪x৩ ম্যাট্রিক্স V ডিফাইন করা
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

# কাস্টম ফাংশন দিয়ে ম্যাট্রিক্স-ম্যাট্রিক্স মাল্টিপ্লিকেশন
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
        
    return result

print("Custom matrix-matrix multiplication:")
print(matrix_matrix_multiplication(U, V))

# NumPy-এর .dot() মেথড ব্যবহার করে
print("NumPy matrix-matrix dot() result:")
print(U.dot(V))

## 5. Identity Matrix

In [ ]:
# ৩x৩ আইডেন্টিটি ম্যাট্রিক্স তৈরি করা
I = np.eye(3)
print("Identity matrix I:")
print(I)

# V ম্যাট্রিক্সের প্রথম ৩টি সারি নিয়ে স্কয়ার ম্যাট্রিক্স তৈরি করে টেস্ট করা
Vs = V[[0, 1, 2]]

print("Vs dot I (Returns Vs back):")
print(Vs.dot(I))

## 6. Matrix Inverse

In [ ]:
# numpy.linalg.inv ব্যবহার করে ইনভার্স ম্যাট্রিক্স বের করা
Vs_inv = np.linalg.inv(Vs)
print("Inverse of Vs (Vs_inv):")
print(Vs_inv)

# ইনভার্স এবং অরিজিনাল ম্যাট্রিক্স গুণ করলে আইডেন্টিটি ম্যাট্রিক্স পাওয়া যায়
print("Vs_inv dot Vs (Returns Identity matrix):")
print(Vs_inv.dot(Vs))